/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.16 .\public\Technical3DModel\AllModels.glb 
*/

import React, { useEffect, useRef, lazy, Suspense } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import { useFrame } from "@react-three/fiber";
import gsap from "gsap";
import * as THREE from "three";
import { ErrorBoundary } from "react-error-boundary";

// Separate main model code so it can be lazy loaded individually
export default function Model(props) {
  try {
    const { nodes, materials, animations } = useGLTF("/models/AllModels.glb", {
      suspense: true,
      prioritizeURL: true,
    });

    const laptopRef = useRef();
    const footballRef = useRef();
    const bloodRef = useRef();
    const workshopRef = useRef();
    const hackathonRef = useRef();

    const { actions } = useAnimations(animations, hackathonRef);

    useFrame((state, delta) => {
      laptopRef.current.rotation.z += 1 * delta;
      bloodRef.current.rotation.z += 1 * delta;
      hackathonRef.current.rotation.z += 1 * delta;

      actions.AstroCreeper_Short_Curcuit_Variant_18?.play();
    });

    useEffect(() => {
      if (props.activeIndex === null) return;
      zoomToModel(props.activeCard);
    }, [props.activeCard]);

    useEffect(() => {
      // Brighten all materials
      Object.values(materials).forEach((material) => {
        // Increase brightness for standard materials
        if (
          material.type.includes("Standard") ||
          material.type.includes("Physical")
        ) {
          material.emissive = new THREE.Color("#222222");
          material.emissiveIntensity = 0.2;
          // Make colors brighter
          if (material.color) {
            const color = material.color.getHSL({});
            material.color.setHSL(
              color.h,
              color.s,
              Math.min(color.l + 0.2, 1.0)
            );
          }
        }
        // For basic materials just brighten color
        else if (material.color) {
          const color = material.color.getHSL({});
          material.color.setHSL(color.h, color.s, Math.min(color.l + 0.3, 1.0));
        }
      });
    }, [materials]);

    const zoomToModel = (positionIndex) => {
      const positions = [
        [
          [0, -0.7, 0],
          [0, -10, 0],
          [0, -10, 0],
          [0, -10, 0],
          [0, -15, 0],
        ],
        [
          [0, 10, 0],
          [0.2, -0.4, 0],
          [0, -8, 0],
          [0, -12, 0],
          [0, -15, 0],
        ],
        [
          [0, 10, 0],
          [0, 5, 0],
          [0, -1, 0],
          [0, -9, 0],
          [0, -12, 0],
        ],
        [
          [0, 15, 0],
          [0, 10, 0],
          [0, 5, 0],
          [-1.3, -0.8, 0],
          [0, -10, 0],
        ],
        [
          [0, 20, 0],
          [0, 15, 0],
          [0, 10, 0],
          [0, 5, 0],
          [0.7, -1, 0],
        ],
        [
          [0, 20, 0],
          [0, 15, 0],
          [0, 10, 0],
          [0, 8, 0],
          [0.7, 8, 0],
        ],
      ];
      gsap.to(laptopRef.current.position, {
        x: positions[positionIndex][0][0],
        y: positions[positionIndex][0][1],
        z: positions[positionIndex][0][2],
        duration: 1,
        ease: "power1.inOut",
      });

      gsap.to(footballRef.current.position, {
        x: positions[positionIndex][1][0],
        y: positions[positionIndex][1][1],
        z: positions[positionIndex][1][2],
        duration: 1,
        ease: "power1.inOut",
      });

      gsap.to(bloodRef.current.position, {
        x: positions[positionIndex][2][0],
        y: positions[positionIndex][2][1],
        z: positions[positionIndex][2][2],
        duration: 1,
        ease: "power1.inOut",
      });

      gsap.to(workshopRef.current.position, {
        x: positions[positionIndex][3][0],
        y: positions[positionIndex][3][1],
        z: positions[positionIndex][3][2],
        duration: 1,
        ease: "power1.inOut",
      });

      gsap.to(hackathonRef.current.position, {
        x: positions[positionIndex][4][0],
        y: positions[positionIndex][4][1],
        z: positions[positionIndex][4][2],
        duration: 1,
        ease: "power1.inOut",
      });
    };

    return (
      <group {...props} dispose={null}>
        <group name="Scene">
          <group
            name="Sketchfab_model"
            ref={laptopRef}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.4}
          >
            <group name="root">
              <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
                <group
                  name="Laptop_1"
                  rotation={[0, -1.571, 0]}
                  scale={[1.5, 1, 1]}
                >
                  <group name="My_Logo_0" />
                  <mesh
                    name="Object_10"
                    geometry={nodes.Object_10.geometry}
                    material={materials.Screen}
                  />
                  <mesh
                    name="Object_4"
                    geometry={nodes.Object_4.geometry}
                    material={materials.Boot_Light}
                  />
                  <mesh
                    name="Object_5"
                    geometry={nodes.Object_5.geometry}
                    material={materials.Keys}
                  />
                  <mesh
                    name="Object_6"
                    geometry={nodes.Object_6.geometry}
                    material={materials.Body}
                  />
                  <mesh
                    name="Object_7"
                    geometry={nodes.Object_7.geometry}
                    material={materials.Body_2}
                  />
                  <mesh
                    name="Object_8"
                    geometry={nodes.Object_8.geometry}
                    material={materials.Key_Light}
                  />
                  <mesh
                    name="Object_9"
                    geometry={nodes.Object_9.geometry}
                    material={materials.Mentese}
                  />
                </group>
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model001"
            ref={footballRef}
            position={[0, 8, -20]}
            rotation={[-0.4, 0, 0]}
            scale={0.5}
          >
            <group
              name="5ce951036d184208ade0e5623cd61d26fbx"
              rotation={[Math.PI / 2, 0, 0]}
              scale={0.01}
            >
              <group name="RootNode">
                <group
                  name="Cube007"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube007_button_trans_0"
                    geometry={nodes.Cube007_button_trans_0.geometry}
                    material={materials.button_trans}
                  />
                </group>
                <group
                  name="Cube011"
                  rotation={[-Math.PI / 2, 0, 0]}
                  scale={100}
                >
                  <mesh
                    name="Cube011_dualsense_0"
                    geometry={nodes.Cube011_dualsense_0.geometry}
                    material={materials.dualsense}
                  />
                </group>
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model002"
            ref={bloodRef}
            position={[0, -10, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
            scale={1.2}
          >
            <group
              name="1f1475f7c5044006b34b68c662f00d3bfbx"
              rotation={[Math.PI / 2, 0, 0]}
            >
              <group name="RootNode001">
                <group name="tent">
                  <mesh
                    name="tent_Tent_0"
                    geometry={nodes.tent_Tent_0.geometry}
                    material={materials.Tent}
                  />
                </group>
              </group>
            </group>
          </group>
          <group
            name="Sketchfab_model003"
            ref={workshopRef}
            position={[0, -15.082, 0]}
            rotation={[-Math.PI / 2, 0, -0.505]}
            scale={2.2}
          >
            <group name="5f995681f5c3426da2f2475c025b8e2eobjcleanermaterialmergergle">
              <mesh
                name="Object_2"
                geometry={nodes.Object_2.geometry}
                material={materials["Gold.001"]}
                position={[1.066, 0.401, 0.082]}
              />
              <mesh
                name="Object_3"
                geometry={nodes.Object_3.geometry}
                material={materials["Grey.001"]}
                position={[1.066, 0.401, 0.082]}
              />
              <mesh
                name="Object_4001"
                geometry={nodes.Object_4001.geometry}
                material={materials["Material.002"]}
                position={[1.066, 0.401, 0.082]}
              />
              <mesh
                name="Object_5001"
                geometry={nodes.Object_5001.geometry}
                material={materials["Microphone.001"]}
                position={[1.066, 0.401, 0.082]}
              />
              <mesh
                name="Object_6001"
                geometry={nodes.Object_6001.geometry}
                material={materials["White.001"]}
                position={[1.066, 0.401, 0.082]}
              />
            </group>
          </group>
          <group
            name="Sketchfab_model004"
            ref={hackathonRef}
            position={[0, -25, 0]}
            rotation={[-Math.PI / 2, 0, 0]}
          >
            <group name="root001">
              <group
                name="GLTF_SceneRootNode001"
                rotation={[Math.PI / 2, 0, 0]}
              >
                <group name="_88">
                  <group
                    name="AstroCreeper_Short_Curcuit_Variant_18"
                    position={[0, 1.5, 0]}
                  >
                    <group
                      name="Body_5"
                      position={[0, -0.313, 0.938]}
                      rotation={[0.175, 0, 0]}
                    >
                      <group name="Body_Layer_4" position={[0, -1.344, -0.916]}>
                        <mesh
                          name="Object_14"
                          geometry={nodes.Object_14.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="Body_3" position={[0, -1.344, -0.916]}>
                        <mesh
                          name="Object_12"
                          geometry={nodes.Object_12.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group
                      name="Head_2"
                      position={[0, 0, 1.063]}
                      rotation={[0.052, 0, 0]}
                    >
                      <group name="Hat_Layer_1" position={[0, -1.552, -0.999]}>
                        <mesh
                          name="Object_9001"
                          geometry={nodes.Object_9001.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="Head_0" position={[0, -1.552, -0.999]}>
                        <mesh
                          name="Object_7001"
                          geometry={nodes.Object_7001.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group
                      name="LeftArm_11"
                      position={[-0.188, 0.625, 0.312]}
                      rotation={[1.485, 0.017, 0.212]}
                    >
                      <group
                        name="Left_Arm_Layer_10"
                        position={[0.313, -1.375, 0]}
                      >
                        <mesh
                          name="Object_24"
                          geometry={nodes.Object_24.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="Left_Arm_9" position={[0.313, -1.375, 0]}>
                        <mesh
                          name="Object_22"
                          geometry={nodes.Object_22.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group
                      name="LeftLeg_17"
                      position={[-0.119, -0.75, 0]}
                      rotation={[Math.PI / 2, 0, -Math.PI / 10]}
                    >
                      <group
                        name="Left_Leg_Layer_16"
                        position={[0.119, -0.75, 0]}
                      >
                        <mesh
                          name="Object_34"
                          geometry={nodes.Object_34.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="Left_Leg_15" position={[0.119, -0.75, 0]}>
                        <mesh
                          name="Object_32"
                          geometry={nodes.Object_32.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group
                      name="RightArm_8"
                      position={[0.313, -0.125, 0.063]}
                      rotation={[Math.PI / 5, 0, 0]}
                    >
                      <group
                        name="Right_Arm_Layer_7"
                        position={[-0.313, -1.375, 0]}
                      >
                        <mesh
                          name="Object_19"
                          geometry={nodes.Object_19.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="Right_Arm_6" position={[-0.313, -1.375, 0]}>
                        <mesh
                          name="Object_17"
                          geometry={nodes.Object_17.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                    <group
                      name="RightLeg_14"
                      position={[0.119, -0.75, 0]}
                      rotation={[Math.PI / 2, 0, Math.PI / 10]}
                    >
                      <group
                        name="Right_Leg_Layer_13"
                        position={[-0.119, -0.75, 0]}
                      >
                        <mesh
                          name="Object_29"
                          geometry={nodes.Object_29.geometry}
                          material={materials.material_0}
                        />
                      </group>
                      <group name="Right_Leg_12" position={[-0.119, -0.75, 0]}>
                        <mesh
                          name="Object_27"
                          geometry={nodes.Object_27.geometry}
                          material={materials.material_0}
                        />
                      </group>
                    </group>
                  </group>
                  <group name="chair_27" position={[0, 0.563, 0.625]}>
                    <group name="cube_19" position={[0, -0.563, 0.312]}>
                      <mesh
                        name="Object_37"
                        geometry={nodes.Object_37.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_20" position={[0, -0.563, 0.312]}>
                      <mesh
                        name="Object_39"
                        geometry={nodes.Object_39.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_21" position={[0, -0.563, 0.312]}>
                      <mesh
                        name="Object_41"
                        geometry={nodes.Object_41.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_22"
                      position={[0, -0.563, 0.312]}
                      rotation={[-1.353, 0, 0]}
                    >
                      <mesh
                        name="Object_43"
                        geometry={nodes.Object_43.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group
                      name="cube_23"
                      position={[0, -0.563, 0.312]}
                      rotation={[-1.353, 0, 0]}
                    >
                      <mesh
                        name="Object_45"
                        geometry={nodes.Object_45.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_24" position={[0, -0.563, 0.312]}>
                      <mesh
                        name="Object_47"
                        geometry={nodes.Object_47.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_25" position={[0, -0.563, 0.312]}>
                      <mesh
                        name="Object_49"
                        geometry={nodes.Object_49.geometry}
                        material={materials.material_1}
                      />
                    </group>
                    <group name="cube_26" position={[0, -0.563, 0.312]}>
                      <mesh
                        name="Object_51"
                        geometry={nodes.Object_51.geometry}
                        material={materials.material_1}
                      />
                    </group>
                  </group>
                  <group
                    name="the_computer_and_the_rest_87"
                    position={[0, 0, -0.063]}
                  >
                    <group name="cube_28">
                      <mesh
                        name="Object_54"
                        geometry={nodes.Object_54.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_29">
                      <mesh
                        name="Object_56"
                        geometry={nodes.Object_56.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_30">
                      <mesh
                        name="Object_58"
                        geometry={nodes.Object_58.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_31">
                      <mesh
                        name="Object_60"
                        geometry={nodes.Object_60.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_32" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_62"
                        geometry={nodes.Object_62.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group
                      name="cube_33"
                      position={[0, 0, 0.063]}
                      rotation={[0, -Math.PI / 8, 0]}
                    >
                      <mesh
                        name="Object_64"
                        geometry={nodes.Object_64.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group
                      name="cube_34"
                      position={[0, 0, 0.063]}
                      rotation={[0, -Math.PI / 8, 0]}
                    >
                      <mesh
                        name="Object_66"
                        geometry={nodes.Object_66.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_35" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_68"
                        geometry={nodes.Object_68.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_36" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_70"
                        geometry={nodes.Object_70.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_37" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_72"
                        geometry={nodes.Object_72.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_38" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_74"
                        geometry={nodes.Object_74.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_39" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_76"
                        geometry={nodes.Object_76.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_40" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_78"
                        geometry={nodes.Object_78.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_41" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_80"
                        geometry={nodes.Object_80.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_42" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_82"
                        geometry={nodes.Object_82.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_43" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_84"
                        geometry={nodes.Object_84.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_44" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_86"
                        geometry={nodes.Object_86.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group
                      name="cube_45"
                      position={[0, 0, 0.063]}
                      rotation={[0, -Math.PI / 8, 0]}
                    >
                      <mesh
                        name="Object_88"
                        geometry={nodes.Object_88.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group
                      name="cube_46"
                      position={[0, 0, 0.063]}
                      rotation={[0, -Math.PI / 8, 0]}
                    >
                      <mesh
                        name="Object_90"
                        geometry={nodes.Object_90.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group
                      name="cube_47"
                      position={[0, 0, 0.063]}
                      rotation={[0, -Math.PI / 8, 0]}
                    >
                      <mesh
                        name="Object_92"
                        geometry={nodes.Object_92.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_48" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_94"
                        geometry={nodes.Object_94.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_49" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_96"
                        geometry={nodes.Object_96.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_50" position={[0, 0, 0.063]}>
                      <mesh
                        name="Object_98"
                        geometry={nodes.Object_98.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_51">
                      <mesh
                        name="Object_100"
                        geometry={nodes.Object_100.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_52">
                      <mesh
                        name="Object_102"
                        geometry={nodes.Object_102.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_53">
                      <mesh
                        name="Object_104"
                        geometry={nodes.Object_104.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_54" rotation={[0, 0.611, 0]}>
                      <mesh
                        name="Object_106"
                        geometry={nodes.Object_106.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_55" rotation={[0, -0.611, 0]}>
                      <mesh
                        name="Object_108"
                        geometry={nodes.Object_108.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_56">
                      <mesh
                        name="Object_110"
                        geometry={nodes.Object_110.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_57">
                      <mesh
                        name="Object_112"
                        geometry={nodes.Object_112.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_58">
                      <mesh
                        name="Object_114"
                        geometry={nodes.Object_114.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_59">
                      <mesh
                        name="Object_116"
                        geometry={nodes.Object_116.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_60">
                      <mesh
                        name="Object_118"
                        geometry={nodes.Object_118.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_63">
                      <mesh
                        name="Object_124"
                        geometry={nodes.Object_124.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_64">
                      <mesh
                        name="Object_126"
                        geometry={nodes.Object_126.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_65">
                      <mesh
                        name="Object_128"
                        geometry={nodes.Object_128.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_66">
                      <mesh
                        name="Object_130"
                        geometry={nodes.Object_130.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_67">
                      <mesh
                        name="Object_132"
                        geometry={nodes.Object_132.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_68">
                      <mesh
                        name="Object_134"
                        geometry={nodes.Object_134.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_69">
                      <mesh
                        name="Object_136"
                        geometry={nodes.Object_136.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_70">
                      <mesh
                        name="Object_138"
                        geometry={nodes.Object_138.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_71">
                      <mesh
                        name="Object_140"
                        geometry={nodes.Object_140.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_72">
                      <mesh
                        name="Object_142"
                        geometry={nodes.Object_142.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_73">
                      <mesh
                        name="Object_144"
                        geometry={nodes.Object_144.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_74">
                      <mesh
                        name="Object_146"
                        geometry={nodes.Object_146.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_75">
                      <mesh
                        name="Object_148"
                        geometry={nodes.Object_148.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_76">
                      <mesh
                        name="Object_150"
                        geometry={nodes.Object_150.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_77">
                      <mesh
                        name="Object_152"
                        geometry={nodes.Object_152.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_78">
                      <mesh
                        name="Object_154"
                        geometry={nodes.Object_154.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_79">
                      <mesh
                        name="Object_156"
                        geometry={nodes.Object_156.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_80">
                      <mesh
                        name="Object_158"
                        geometry={nodes.Object_158.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_81">
                      <mesh
                        name="Object_160"
                        geometry={nodes.Object_160.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_82">
                      <mesh
                        name="Object_162"
                        geometry={nodes.Object_162.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_83" rotation={[0, -0.611, 0]}>
                      <mesh
                        name="Object_164"
                        geometry={nodes.Object_164.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_84">
                      <mesh
                        name="Object_166"
                        geometry={nodes.Object_166.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group name="cube_85" rotation={[0, 0.611, 0]}>
                      <mesh
                        name="Object_168"
                        geometry={nodes.Object_168.geometry}
                        material={materials.material_3}
                      />
                    </group>
                    <group
                      name="cylinder_62"
                      position={[0, 0, 0.313]}
                      rotation={[0, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="Object_122"
                        geometry={nodes.Object_122.geometry}
                        material={materials.material_2}
                      />
                    </group>
                    <group
                      name="torus_61"
                      position={[0.006, 0, 0.313]}
                      rotation={[Math.PI / 2, 0, Math.PI / 2]}
                    >
                      <mesh
                        name="Object_120"
                        geometry={nodes.Object_120.geometry}
                        material={materials.material_2}
                      />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    );
  } catch (error) {
    console.error("Failed to load 3D model:", error);
    return <div>Failed to load 3D model. Please try again later.</div>;
  }
}

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

// Direct imports instead of lazy loading here
import ModelmanComponent from "./ModelComponents/Modelman";
import BookModelComponent from "./ModelComponents/BookModel";
import GogreenModelComponent from "./ModelComponents/GogreenModel";

// Export directly without lazy loading
export const Modelman = ModelmanComponent;
export const BookModel = BookModelComponent;
export const GogreenModel = GogreenModelComponent;
