/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function ManModel() {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('/tesst.glb')
  const { actions } = useAnimations(animations, group)
  console.log(actions)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="Armature" rotation={[Math.PI / 2, 0, 0]} scale={0.01}>
          <primitive object={nodes.rp_nathan_animated_003_walking_root} />
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/tesst.glb')
